### ISSUE TITLE
Unexpected behavior detected in multiply function when determining peak of function with y-values

### ISSUE THREAD

**Issue by josephhughes** [neherlab/treetime#239]
When running` treetime 0.10.0 ` with the following command:

`/home1/jh212a/.local/bin/treetime --aln /home5/nCov/Joseph/Phylogeny/GISAID_1Feb2023/analysis/alignment/Scotland89220_greatancestoralignment.fasta --clock-rate 0.0008 --clock-std-dev 0.0004 --confidence --clock-filter 8 --keep-root --max-iter 10 --tree /home5/nCov/Joseph/Phylogeny/GISAID_1Feb2023/analysis/trees/Scotland89220_greatancestorpruned.tre --dates /home5/nCov/Joseph/Phylogeny/GISAID_1Feb2023/analysis/filteredsamples/Scotland89220_filtered_greatancestor_tipnames.txt --name-column 'sequence_name' --date-column 'sample_date' --outdir /home5/nCov/Joseph/Phylogeny/GISAID_1Feb2023/analysis/greatancestortreetime/Scotland89220 --verbose 5
`
I get the following error message:

```
3554.27 ----ClockTree._ml_t_root_to_leaves: computed convolution with 9053
            points at node NODE_0000009
3554.29 ----ClockTree._ml_t_root_to_leaves: computed convolution with 8023
            points at node NODE_0000010
3554.31 ----ClockTree._ml_t_root_to_leaves: computed convolution with 7511
            points at node NODE_0000011
3554.32 ----ClockTree._ml_t_root_to_leaves: computed convolution with 7239
            points at node NODE_0000012
3554.34 ----ClockTree._ml_t_root_to_leaves: computed convolution with 7034
            points at node NODE_0000013
Traceback (most recent call last):
  File "/home1/jh212a/.local/lib/python3.8/site-packages/treetime/distribution.py", line 118, in multiply
    peak = y_vals.min()
  File "/usr/local/lib/python3.8/dist-packages/numpy/core/_methods.py", line 43, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation minimum which has no identity

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home1/jh212a/.local/lib/python3.8/site-packages/treetime/treetime.py", line 57, in run
    return self._run(**kwargs)
  File "/home1/jh212a/.local/lib/python3.8/site-packages/treetime/treetime.py", line 341, in _run
    self.make_time_tree(**tt_kwargs)
  File "/home1/jh212a/.local/lib/python3.8/site-packages/treetime/clock_tree.py", line 374, in make_time_tree
    self._ml_t_marginal()
  File "/home1/jh212a/.local/lib/python3.8/site-packages/treetime/clock_tree.py", line 747, in _ml_t_marginal
    node.marginal_pos_LH = NodeInterpolator.multiply((node.msg_from_parent, node.subtree_distribution))
  File "/home1/jh212a/.local/lib/python3.8/site-packages/treetime/distribution.py", line 120, in multiply
    raise TreeTimeUnknownError("Error: Unexpected behavior detected in multiply function"
treetime.TreeTimeUnknownError: Error: Unexpected behavior detected in multiply function when determining peak of function with y-values '[]'.

If you see this error please let us know by filling an issue at: 
https://github.com/neherlab/treetime/issues

ERROR: Error: Unexpected behavior detected in multiply function when determining peak of function with y-values '[]'.

If you see this error please let us know by filling an issue at: 
https://github.com/neherlab/treetime/issues 
 
ERROR in TreeTime.run: An error occurred which was not properly handled in TreeTime. If this error persists, please let us know by filing a new issue including the original command and the error above at: https://github.com/neherlab/treetime/issues 
```

Any advice would be very welcome.

Bw,
Joseph

**Comment by rneher** [comment]
It looks like you are running this on a large phylogeny that probably has pretty big polytomies, right? The error you are facing happens when temporal distributions are passed down via convolution along cater-pillar like polytomies. One easy fix could be to add use `--stochastic-resolve` which will resolve polytomies in a different (more sensible) way that avoids creating very unbalanced trees.

**Comment by josephhughes** [comment]
I get a slightly different error now:

```
4.31    ###TreeTime.run: ITERATION 1 out of 10 iterations

4.31    -TreeTime.resolve_polytomies: resolving multiple mergers...
4.31    ---TreeTime.generate_subtree: node NODE_0000000 has 4 children. 3 have
           mutations. The time window for coalescence is 1.4449e-04
Traceback (most recent call last):
  File "/home1/jh212a/.local/lib/python3.8/site-packages/treetime/treetime.py", line 57, in run
    return self._run(**kwargs)
  File "/home1/jh212a/.local/lib/python3.8/site-packages/treetime/treetime.py", line 286, in _run
    n_resolved = self.resolve_polytomies(stochastic_resolve=stochastic_resolve)
  File "/home1/jh212a/.local/lib/python3.8/site-packages/treetime/treetime.py", line 618, in resolve_polytomies
    self.generate_subtree(n)
  File "/home1/jh212a/.local/lib/python3.8/site-packages/treetime/treetime.py", line 818, in generate_subtree
    if self.merger_model is None:
AttributeError: 'TreeTime' object has no attribute 'merger_model'

ERROR: 'TreeTime' object has no attribute 'merger_model' 
 
ERROR in TreeTime.run: An error occurred which was not properly handled in TreeTime. If this error persists, please let us know by filing a new issue including the original command and the error above at: https://github.com/neherlab/treetime/issues 

```

I've re-installed as to me is seemed like it was something to do with a module missing but I still get the error.

**Comment by josephhughes** [comment]
Thank you for developing tree time and for taking the time to look into this. The error is now a few lines down:

```

4.21	###TreeTime.run: ITERATION 1 out of 10 iterations

4.21	-TreeTime.resolve_polytomies: resolving multiple mergers...
4.21	---TreeTime.generate_subtree: node NODE_0000000 has 4 children. 3 have
    	   mutations. The time window for coalescence is 1.4449e-04
Traceback (most recent call last):
  File "/home1/jh212a/.local/lib/python3.8/site-packages/treetime/treetime.py", line 57, in run
    return self._run(**kwargs)
  File "/home1/jh212a/.local/lib/python3.8/site-packages/treetime/treetime.py", line 286, in _run
    n_resolved = self.resolve_polytomies(stochastic_resolve=stochastic_resolve)
  File "/home1/jh212a/.local/lib/python3.8/site-packages/treetime/treetime.py", line 618, in resolve_polytomies
    self.generate_subtree(n)
  File "/home1/jh212a/.local/lib/python3.8/site-packages/treetime/treetime.py", line 821, in generate_subtree
    coalescent_rate = self.merger_model.branch_merger_rate(t) + mutation_rate
AttributeError: 'TreeTime' object has no attribute 'merger_model'

ERROR: 'TreeTime' object has no attribute 'merger_model' 
 
ERROR in TreeTime.run: An error occurred which was not properly handled in TreeTime. If this error persists, please let us know by filing a new issue including the original command and the error above at: https://github.com/neherlab/treetime/issues 

```

**Comment by rneher** [comment]
that was silly of me. I had the conditions of the check inverted. Could you try again after installing `master`?

**Comment by corneliusroemer** [comment]
I've just hit this issue myself running a monkeypox build on v0.10.0 release.

@rneher I'll send you the files via Slack for debugging in case this isn't fixed entirely already.

**Comment by corneliusroemer** [comment]
Hmm, I tested this on master and it doesn't seem to work. Here's my full error:

```log
<--- SNIP --- >
616.52  ###TreeTime.run: ITERATION 2 out of 2 iterations
Traceback (most recent call last):
  File "/Users/corneliusromer/code/treetime/treetime/distribution.py", line 118, in multiply
    peak = y_vals.min()
           ^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/treetime/lib/python3.11/site-packages/numpy/core/_methods.py", line 45, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial, where)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: zero-size array to reduction operation minimum which has no identity

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/corneliusromer/code/treetime/treetime/treetime.py", line 57, in run
    return self._run(**kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/corneliusromer/code/treetime/treetime/treetime.py", line 330, in _run
    self.calc_rate_susceptibility(rate_std=vary_rate, params=tt_kwargs)
  File "/Users/corneliusromer/code/treetime/treetime/clock_tree.py", line 882, in calc_rate_susceptibility
    self.make_time_tree(**params)
  File "/Users/corneliusromer/code/treetime/treetime/clock_tree.py", line 374, in make_time_tree
    self._ml_t_marginal()
  File "/Users/corneliusromer/code/treetime/treetime/clock_tree.py", line 631, in _ml_t_marginal
    node.product_of_child_messages = Distribution.multiply(msgs_to_multiply)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/corneliusromer/code/treetime/treetime/distribution.py", line 120, in multiply
    raise TreeTimeUnknownError("Error: Unexpected behavior detected in multiply function"
treetime.TreeTimeUnknownError: Error: Unexpected behavior detected in multiply function when determining peak of function with y-values '[]'.

ERROR: Error: Unexpected behavior detected in multiply function when determining peak of function with y-values '[]'.
```

**Comment by josephhughes** [comment]
It's run a lot further than previously:

```

282.52  --ClockTree.date2dist: Setting new molecular clock. rate=8.000e-04,
          R^2=0.3111
282.52  --ClockTree.init_date_constraints: node date constraints objects...
282.52  --ClockTree - Marginal reconstruction using FFT convolution:  Propagating
          leaves -> root...


Traceback (most recent call last):
  File "/home1/jh212a/.local/lib/python3.8/site-packages/treetime/distribution.py", line 118, in multiply
    peak = y_vals.min()
  File "/usr/local/lib/python3.8/dist-packages/numpy/core/_methods.py", line 43, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation minimum which has no identity

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home1/jh212a/.local/lib/python3.8/site-packages/treetime/treetime.py", line 57, in run
    return self._run(**kwargs)
  File "/home1/jh212a/.local/lib/python3.8/site-packages/treetime/treetime.py", line 341, in _run
    self.make_time_tree(**tt_kwargs)
  File "/home1/jh212a/.local/lib/python3.8/site-packages/treetime/clock_tree.py", line 374, in make_time_tree
    self._ml_t_marginal()
  File "/home1/jh212a/.local/lib/python3.8/site-packages/treetime/clock_tree.py", line 631, in _ml_t_marginal
    node.product_of_child_messages = Distribution.multiply(msgs_to_multiply)
  File "/home1/jh212a/.local/lib/python3.8/site-packages/treetime/distribution.py", line 120, in multiply
    raise TreeTimeUnknownError("Error: Unexpected behavior detected in multiply function"
treetime.TreeTimeUnknownError: Error: Unexpected behavior detected in multiply function when determining peak of function with y-values '[]'.

If you see this error please let us know by filling an issue at: 
https://github.com/neherlab/treetime/issues

ERROR: Error: Unexpected behavior detected in multiply function when determining peak of function with y-values '[]'.

If you see this error please let us know by filling an issue at: 
https://github.com/neherlab/treetime/issues 
 
ERROR in TreeTime.run: An error occurred which was not properly handled in TreeTime. If this error persists, please let us know by filing a new issue including the original command and the error above at: https://github.com/neherlab/treetime/issues 

```

**Comment by corneliusroemer** [comment]
I get the same (?) bug also on treetime 0.9.6:

```log
  File "/opt/homebrew/Caskroom/miniforge/base/envs/treetime9/lib/python3.11/site-packages/treetime/distribution.py", line 121, in multiply
    ind = (y_vals-peak)<BIG_NUMBER/1000
           ^^^^^^
UnboundLocalError: cannot access local variable 'peak' where it is not associated with a value
```

<details>

```log
[Tue May 16 21:16:28 2023]
rule refine:
    input: results/mpxv/tree_fixed.nwk, results/mpxv/masked.fasta, results/mpxv/metadata.tsv
    output: results/mpxv/tree.nwk, results/mpxv/branch_lengths.json
    jobid: 4
    reason: Missing output files: results/mpxv/tree.nwk, results/mpxv/branch_lengths.json
    wildcards: build_name=mpxv
    resources: tmpdir=/var/folders/qf/4kkcfypx0gbfb0t9336522_r0000gn/T


        augur refine             --tree results/mpxv/tree_fixed.nwk             --alignment results/mpxv/masked.fasta             --metadata results/mpxv/metadata.tsv             --output-tree results/mpxv/tree.nwk             --timetree             --root min_dev             --precision 3             --keep-polytomies             --clock-rate 3e-6             --clock-std-dev 6e-6             --use-fft             --output-node-data results/mpxv/branch_lengths.json             --coalescent opt             --date-inference marginal             --date-confidence             --clock-filter-iqd 0
        
augur refine is using TreeTime version 0.9.6
 
55.99   WARNING: Previous versions of TreeTime (<0.7.0) RECONSTRUCTED sequences of
        tips at positions with AMBIGUOUS bases. This resulted in unexpected
        behavior is some cases and is no longer done by default. If you want to
        replace those ambiguous sites with their most likely state, rerun with
        `reconstruct_tip_states=True` or `--reconstruct-tip-states`.

295.82  TreeTime.reroot: with method or node: min_dev

295.82  TreeTime.reroot: rerooting will account for covariance and shared
        ancestry.

592.25  ###TreeTime.run: INITIAL ROUND

605.72  TreeTime.reroot: with method or node: min_dev

605.72  TreeTime.reroot: rerooting will account for covariance and shared
        ancestry.

607.43  ###TreeTime.run: rerunning timetree after rerooting
Warning: evaluating log probability of a delta distribution.
Warning: evaluating log probability of a delta distribution.
Warning: evaluating log probability of a delta distribution.
Warning: evaluating log probability of a delta distribution.
Warning: evaluating log probability of a delta distribution.
Warning: evaluating log probability of a delta distribution.
Warning: evaluating log probability of a delta distribution.
Warning: evaluating log probability of a delta distribution.
Warning: evaluating log probability of a delta distribution.
Warning: evaluating log probability of a delta distribution.
Warning: evaluating log probability of a delta distribution.
Warning: evaluating log probability of a delta distribution.
Warning: evaluating log probability of a delta distribution.
Warning: evaluating log probability of a delta distribution.
Warning: evaluating log probability of a delta distribution.

875.27  ###TreeTime.run: ITERATION 1 out of 2 iterations
Warning: evaluating log probability of a delta distribution.
Warning: evaluating log probability of a delta distribution.
Warning: evaluating log probability of a delta distribution.
Warning: evaluating log probability of a delta distribution.
Warning: evaluating log probability of a delta distribution.

964.32  ###TreeTime.run: ITERATION 2 out of 2 iterations
Warning: evaluating log probability of a delta distribution.
Warning: evaluating log probability of a delta distribution.
Warning: evaluating log probability of a delta distribution.
Warning: evaluating log probability of a delta distribution.
Warning: evaluating log probability of a delta distribution.
Warning: evaluating log probability of a delta distribution.
Warning: evaluating log probability of a delta distribution.
Warning: evaluating log probability of a delta distribution.
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/treetime9/lib/python3.11/site-packages/treetime/treetime.py", line 57, in run
    return self._run(**kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/treetime9/lib/python3.11/site-packages/treetime/treetime.py", line 329, in _run
    self.calc_rate_susceptibility(rate_std=vary_rate, params=tt_kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/treetime9/lib/python3.11/site-packages/treetime/clock_tree.py", line 880, in calc_rate_susceptibility
    self.make_time_tree(**params)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/treetime9/lib/python3.11/site-packages/treetime/clock_tree.py", line 378, in make_time_tree
    self._ml_t_marginal()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/treetime9/lib/python3.11/site-packages/treetime/clock_tree.py", line 634, in _ml_t_marginal
    node.product_of_child_messages = Distribution.multiply(msgs_to_multiply)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/treetime9/lib/python3.11/site-packages/treetime/distribution.py", line 121, in multiply
    ind = (y_vals-peak)<BIG_NUMBER/1000
           ^^^^^^
UnboundLocalError: cannot access local variable 'peak' where it is not associated with a value
```

</details>

**Comment by corneliusroemer** [comment]
Oh I see, so now we're back to #171, does this mean we can close this here as resolved and duplicate for the remainder?

**Comment by rneher** [comment]
@josephhughes to expand a bit. this error surfaces when during the aggregation of probability distribution from lots of branches the permissible region shrinks so much that it falls below the discretization range -- so this is essentially a numerical problem. This used to happen in large asymmetrically resolved polytomies and that is why I suggested to use `--stochastic-resolve` (which uncovered other errors that were easy to fix). But this problem can also happen otherwise, in particular when there are serious outliers or misdated sequences.  As this happens only in large trees with anomalous constellations, it is hard to debug. If you are willing to share the data you run this one, I can try to dig a little deeper.

**Comment by josephhughes** [comment]
The three input files are [here](https://www.dropbox.com/sh/r8lsz4f6umkieqd/AACJ6KCSW0hLHQYEZY0ElcIHa?dl=0)
I hope they are accessible.
Thanks.

**Comment by rneher** [comment]
thanks for sharing these files. The problem seems to be that your input tree has branch length is units of mutations/genome rather than mutations/site. TreeTime expects the latter. It prints a warning at the beginning, but TreeTime should handle this a bit more gracefully. 

If you rescale your branch length by 1/29903, it runs fine. I attached the rescaled tree and would suggest to run treetime like this:
```
treetime --aln Scotland89220_greatancestoralignment.fasta --tree rescaled.nwk \
     --clock-rate 0.0008 --clock-std-dev 0.0004 --keep-root  \                                                                                                                                                    
     --dates Scotland89220_filtered_greatancestor_tipnames.txt \                                        
     --name-column 'sequence_name' --date-column 'sample_date' \                                        
     --stochastic-resolve --clock-filter 8 --max-iter 4 --time-marginal always \
     --coalescent opt --verbose 4 --confidence \
     --outdir scotland_test_rescaled
```
[rescaled.txt](https://github.com/neherlab/treetime/files/11496589/rescaled.txt)

**Comment by rneher** [comment]
no worries. TreeTime should check the input more carefully -- so this is mostly on the software :sweat_smile:
